version: '3.9'

services:
  restest1:
    container_name: restest1
    image: restest1:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - 3000:3000
    working_dir: /app/src
    volumes:
      - .:/app/src
    command: npm run start:dev
    #restart: unless-stopped